services:
  vadapp-gpu:
    container_name: vadapp-gpu
    build:
      context: .
      dockerfile: ./Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "8501:8501"
    env_file:
      - .env
  vadapp-cpu:
    container_name: vadapp-cpu
    build:
      context: .
      dockerfile: ./Dockerfile.cpu
    ports:
      - "8501:8501"
    env_file:
      - .env
