dataset_cfg:
  clip_len: 32
  feature_dim: 768
  feature_name: swin_rgb
  max_seq_len: 32
  num_workers: 4
  sampling_rate: 2
  streaming: false
logging_cfg:
  ckpt_interval_epochs: 2
  exp_name: svm-swin
  log_dir: logs/wandb/run-20240110_054200-hqx4vhgn/files
  log_interval_steps: 10
  test_interval_epochs: 2
  test_metric: ap
model_cfg:
  dropout_prob: 0.6
  loss:
    margin: 1
  model_name: svm_baseline
optimizer_cfg:
  lr: 0.001
  weight_decay: 0.01
training_cfg:
  batch_size: 128
  max_epochs: 50
  resume_ckpt_type: null
  resume_run_id: null
  seed: 2233
